name = "tpp-app"
compatibility_date = "2023-12-01"

# Configuração do banco de dados D1
[[d1_databases]]
binding = "DB"                # Nome da variável de ambiente
database_name = "tpp-db"      # Nome do banco de dados
database_id = "local"         # ID para desenvolvimento local
